### ISSUE TITLE
"Clémenceau" à remplacer par "Clemenceau" pour l'accentuation

### ISSUE THREAD

**Issue by cquest** [etalab/ban-data#10]
Clemenceau (Georges) s'écrit sans accent.

**Comment by FrancoisVIGN** [comment]
Dans la base de production IGN, tous les noms de rues sont en Majuscules et sans accentuation

**Comment by cquest** [comment]
Oui, je suis au courant pour le contenu des bases internes IGN, mais la sortie BAN étant ré-accentuée à l'aide d'un dictionnaire il semble que celui-ci doit contenir un "clémenceau" à remplacer en "clemenceau" vu que c'est l'orthographe correcte de ce nom.

Ce dictionaire utilisé pourrait d'ailleurs être partagé ici pour permettre de proposer des améliorations de celui-ci.

**Comment by ghost** [comment]
correction en cours.

**Comment by cquest** [comment]
Corrigé dans la livraison du 11-04-2015

**Comment by ghost** [comment]
:-)
