### ISSUE TITLE
BAN_odbl_14 : cas de dénomination inappropriée (doublon de rappel de communes)

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#101]
14014_XXXX_65b2b3 

{"id":"14014_XXXX_65b2b3","type":"street","name":"**Chemin des Pèlerins (Colomby-Sur-Thaon) (Colomby-sur-Thaon)**","postcode":"14610","citycode":"14014","lon":-0.421263,"lat": 49.265826,"city":"Colomby-Anguerny","context":"14, Calvados, Basse-Normandie","importance":0.0041,"housenumbers":{"5067":{"lat":49.265826,"lon":-0.421263,"id":"ADRNIVX_0000000358669538"}}}

? Il y a un (Colomby-Sur-Thaon) en trop !

Merci de votre réponse

**Comment by cquest** [comment]
En principe réglé par: https://github.com/etalab/ban-data/commit/86b92b7ed17245fdc5f990b5ee3580c05dee58e0
