### ISSUE TITLE
BAN_odbl_76 : absence d'intégrité entre street et municipality !

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#103]
De façon inattendue, on constate avec un vif regret qu'il manque la **municipality 76095**, soit **_Bihorel_** quand curieusement son ex-partenaire de quelques temps **Bois-Guillaume** est présente deux fois dans le fichier !!

{"id": "76108","type": "municipality","name": "Bois-Guillaume","postcode": "76230","citycode": "76108","lat": "49.470068","lon": "1.118692","city": "Bois-Guillaume","context": "76, Seine-Maritime, Haute-Normandie", "population": 13.6, "adm_weight": 2, "importance": 0.3781}
{"id": "76108","type": "municipality","name": "Bois-Guillaume","postcode": "76230","citycode": "76108","lat": "49.470068","lon": "1.118692","city": "Bois-Guillaume","context": "76, Seine-Maritime, Haute-Normandie", "population": 13.6, "adm_weight": 2, "importance": 0.3781}

**SOS !**

**Comment by parville** [comment]
On peut estimer qu'il conviendrait de réaliser le dit contrôle d'intégrité (tous les citycode déclarés sont des municipality) avant de livrer les données ?

**Comment by cquest** [comment]
Bihorel manque effectivement... un vrai feuilleton que ces deux là ;)

Je viens de corriger ça pour le prochain traitement.
