### ISSUE TITLE
BAN_odbl_xx (liv 2017sem06) Absence de prise en compte des fusions 2017 pour les "municipality"

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#107]
Exemple **14011** désigne dorénavant **Aurseulles** mais la donnée "municipality" désigne toujours **Anctoville**

Merci

**Comment by cquest** [comment]
En attente d'info pour les codes postaux et aussi d'intégration des fusions en amont par l'IGN.

Je vais intégrer les fusions 2017 sans attendre ceci pour le traitement ODbL...

**Comment by cquest** [comment]
L'IGN a opéré à la fusion des communes au 1/1/2017 sur les livraisons BANv0 depuis le 22/1.
J'ajoute le traitement pour avoir les noms des anciennes communes

**Comment by cquest** [comment]
Fusions du 1/1/2017 intégrées... en complément de la précédente vague.

On a les deux anciens noms de commune qui sont ajoutés si besoin, ainsi que les différents codes INSEE (pour permettre au filtre sur citycode de fonctionner qu'on passe le code INSEE actuel ou précédents).

Je charge dès que possible l'API de test (devapi-adresse.data.gouv.fr)

**Comment by cquest** [comment]
L'API est rechargée.

Exemples (pour les fusions 2017):

http://devapi-adresse.data.gouv.fr/search?q=rue%20des%20ponts%20aillant%20sur%20tholon
Commune nouvelle: Montholon, commune déléguée: Aillant-sur-Tholon (chef-lieu)

http://devapi-adresse.data.gouv.fr/search?q=place%20de%20l%27%C3%A9glise%20volgre
citycode indique le nouveau code INSEE (89003)

Recherche nom de voie, mais avec un filtre sur l'ancien code INSEE (commune déléguée):
http://devapi-adresse.data.gouv.fr/search?q=place%20de%20l%27%C3%A9glise&citycode=89484

Il reste à charger les municipality...

**Comment by cquest** [comment]
corrigé par https://github.com/etalab/ban-data/commit/4b41529173b693d2f8e47aa0bf46de109688c804
