### ISSUE TITLE
Échappement des doubles quotes

### ISSUE THREAD

**Issue by nsagot** [etalab/ban-data#111]
Bonjour, 

Je chercher à importer dans une base mongodb le fichier json général. 
Le soucis est que les doubles quotes à l'intérieur de champs de valeur de ne sont pas échappés. Ce qui fais arrêter mon importation.  

Autre soucis également, des antislash sont présents avant le quote de fin de chaîne ce qui échappe ce quote et fais aussi arrêter l'importation. 

Pour suivre la norme JSON, il rajouter ces deux opérations d'échappement.

**Comment by cquest** [comment]
ça sera réglé dans le prochain export json...
