### ISSUE TITLE
Dieppe en double

### ISSUE THREAD

**Issue by yohanboniface** [etalab/ban-data#114]
```
203:{"id": "76217","type": "municipality","name": "Dieppe","postcode": "76200","citycode": "76217","lat": 49.921511,"lon": 1.076982,"city": "Dieppe","context": "76, Seine-Maritime, Normandie (Haute-Normandie)", "population": 32.7, "adm_weight": 3, "importance": 0.5452}
204:{"id": "76217_76370","type": "municipality","name": "Dieppe","postcode": "76370","citycode": "76217","lat": 49.921511,"lon": 1.076982,"city": "Dieppe","context": "76, Seine-Maritime, Normandie (Haute-Normandie)", "population": 32.7, "adm_weight": 3, "importance": 0.5452}
```

**Comment by cquest** [comment]
1 Dieppe, mais 2 codes postaux...

Le problème c'est que seul le premier postcode sera proposé en autocomplétion si je remplace par:
`{"id": "76217","type": "municipality","name": "Dieppe","postcode": ["76200","76370"],"citycode": "76217","lat": 49.921511,"lon": 1.076982,"city": "Dieppe","context": "76, Seine-Maritime, Normandie (Haute-Normandie)", "population": 32.7, "adm_weight": 3, "importance": 0.5452}`
