### ISSUE TITLE
ID en doublons...

### ISSUE THREAD

**Issue by cquest** [etalab/ban-data#13]
L'ID n'est pas unique ?

Nombre d'ID doublons identifiés par département dans la livraison du 20-03-2015 (départements 01 à 22)

 dept | nb_id_doublons 
------+----------------
 01   |           5456
 02   |           5961
 03   |           1831
 04   |           6977
 05   |           1299
 06   |          11321
 07   |           6934
 08   |           4811
 09   |           3075
 10   |           3952
 11   |           5634
 12   |           6591
 13   |          22856
 14   |          10150
 15   |           1605
 16   |           6494
 17   |           9594
 18   |           3142
 19   |           5694
 21   |           3374
 22   |          15186
 2A   |           1188
 2B   |           2842

Et en nombre total d'adresses cela donne:

dept | total  | id_distincts | doublons 
------+--------+--------------+----------
 01   | 287119 |       284372 |     2747
 02   | 259637 |       256486 |     3151
 03   | 192078 |       191142 |      936
 04   | 108632 |       104997 |     3635
 05   |  79047 |        78384 |      663
 06   | 283452 |       277679 |     5773
 07   | 204942 |       201350 |     3592
 08   | 151926 |       149421 |     2505
 09   | 117821 |       116270 |     1551
 10   | 147923 |       145862 |     2061
 11   | 276841 |       273985 |     2856
 12   | 176393 |       173062 |     3331
 13   | 614499 |       602669 |    11830
 14   | 330885 |       325667 |     5218
 15   |  98147 |        97319 |      828
 16   | 219126 |       215879 |     3247
 17   | 431909 |       426987 |     4922
 18   | 188813 |       187208 |     1605
 19   | 156178 |       153241 |     2937
 21   | 220054 |       218367 |     1687
 22   | 387521 |       379788 |     7733
 2A   |  60541 |        59862 |      679
 2B   |  72802 |        71126 |     1676

**Comment by ghost** [comment]
si l'iD est unique je t'ai expliqué dans le commentaire sur le 33 d'où cela vient!

**Comment by cquest** [comment]
On fermera à la prochaine livraison qui devrait avoir réglé ce problème.

**Comment by cquest** [comment]
Problème réglé
