### ISSUE TITLE
Communes sans aucune adresse ?

### ISSUE THREAD

**Issue by cquest** [etalab/ban-data#16]
Il n'y a aucune adresse pour les communes suivantes:

09304 Suzan
29084 Île-Molène
52465 Saulxures
55050 Bezonvaux
55138 Culey
55239 Haumont-près-Samogneux
55307 Louvemont-Côte-du-Poivre

Culey est un cas particulier car issue de la dé-fusion avec Loisey (55298)
Elles sont désormais dans le COG 2015: http://www.insee.fr/fr/methodes/nomenclatures/cog/telechargement.asp?annee=2015

**Comment by ghost** [comment]
je ne sais pas ce qu'il en est, je consulte la production, je ne me suis pas abonnée aux issues, du coup je ne l'ai pas vue.

**Comment by FrancoisVIGN** [comment]
Suzan n'est pas cadastré. 
Ile Molène n'est pas cadastré.

Culey disposent d'adresses

pour Bezonvaux, Haumont et Louvemont, il s'agit de commune morte pour la France (http://fr.wikipedia.org/wiki/Maire_%28France%29#Communes_mortes_pour_la_France)

**Comment by cquest** [comment]
Joie des cas particuliers ;)

Effectivement, pour les communes mortes pour la France, l'absence totale d'adresse est cohérente. Je vais les retirer explicitement de mes tests.

Pour les communes non cadastrées, celles-ci n'ont vraiment aucune adresse ou bien manque-t-on d'adresses ?

Et pour Saulxures, il y a une explication ?

**Comment by FrancoisVIGN** [comment]
je prolonge mon investigation !

**Comment by cquest** [comment]
Des nouvelles ?

7 communes concernées sur la livraison 20150705:
14517: POUSSY-LA-CAMPAGNE
21221: CUSSY-LA-COLONNE
21675: VIANGES
21694: VILLEFERRY
52465: SAULXURES
54354: MARTHEMONT
62210: CANTELEUX

**Comment by FrancoisVIGN** [comment]
Après analyse de la base de production, il s'avère que :
![image](https://cloud.githubusercontent.com/assets/11737792/9087385/981b5e50-3b8a-11e5-9f8b-abd72b38562b.png)
Les adresses supprimées correspondent à des adresses ayant considérées comme attachées à une adresse ou un lieu dit inexistant
