### ISSUE TITLE
Changes in the Addok export

### ISSUE THREAD

**Issue by yohanboniface** [etalab/ban-data#18]
As discussed, those are some micro changes made on the fly by addok, doing them here would make the import in addok generic.
- [x] create the `context` key, by concatenating the department id, the department name (only if different from the city), the région name
- [x] replace "hamlet" and "place" types by "locality" (do we still want that? Not sure we are totally consistent on the type values actually)
- [x] when type is in `['village', 'town', 'city', 'commune', 'locality']`, I've sometime noticed that the `name` can be empty, so I fallback on `city` in this case

Thanks :)

**Comment by cquest** [comment]
Fixed in https://github.com/etalab/ban-data/commit/143f57d18cbf57f7db6e85b315ecf97f7883c620

**Comment by cquest** [comment]
Addok import still expect "departement"... https://github.com/etalab/addok/blob/master/addok/batch/bano.py#L17

**Comment by yohanboniface** [comment]
I've not commited the change yet, you have been faster! ;)

**Comment by yohanboniface** [comment]
Pushed a quick and dirty fix for that, I'll refactor it cleany this morning :)
