### ISSUE TITLE
DOM TOM en cours

### ISSUE THREAD

**Issue by ghost** [etalab/ban-data#19]
Finalement on va livrer au plus tard demain matin mais sans le nom afnor et le libellé acheminement. On fera mieux pour la prochaine livraison dans une semaine. ce qui est une bonne nouvelle par contre c'est qu'on a monté un mécanisme pseudo industriel et non un truc sale à la main.

**Comment by ghost** [comment]
martinique et guadeloupe sont livrées.

**Comment by cquest** [comment]
971 à 974 reçus... autres DOM à venir ? Mayotte ?

**Comment by ghost** [comment]
a priori pas ce soir, Mes équipes sont rentrées chez elles et depuis chez moi je n'ai pas d'accès à la BDUni. On verra demain matin pour la suite mais on est presque au bout. désolée pour les délais mais bon on peut partir comme ça au pire. quitte à recompléter après l'ouverture

**Comment by cquest** [comment]
Mayotte reçu :)
