### ISSUE TITLE
Absence du libellé d'acheminement sur la version "licence BAN"

### ISSUE THREAD

**Issue by cquest** [etalab/ban-data#2]
Les premiers exports sur le 33 ne contiennent pas les libellés d'acheminement.

**Comment by ghost** [comment]
il me semble qu'on les a ajoutés sur la livraison suivante, je revérifie, mais sinon on ne le fera pas d'ici la sortie.

**Comment by ghost** [comment]
on les a effectivement ajoutés dans la livraison du 11 avril

**Comment by ghost** [comment]
je propose qu'on ferme cette issue

**Comment by cquest** [comment]
Corrigé dans la livraison du 11-04-2015

Par contre ils ont été ajoutés aussi par erreur dans la version odbl (je les ai supprimé avant mes traitements)
