### ISSUE TITLE
Libellé acheminement obsolète 76230 ; BOIS GUILLAUME BIHOREL

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#20]
Selon le site de La Poste , 76230 correspond à BOIS GUILLAUME et non pas à BOIS GUILLAUME BIHOREL.

**Comment by ghost** [comment]
Alors là pour le coup ça vient des données fournies par le service national de l adresse donc je ne sais pas qui a raison. Je leur poserai la question à l occasion.

**Comment by parville** [comment]
En tout cas vous verrez sur data.gouv.fr que j'ai notifié à la poste qu'il y avait un soucis sur BOIS-GUILLAUME et BIHOREL ! Réponse récente : nous n'avions pas noté la défusion des deux communes ! :angel:

**Comment by parville** [comment]
La remarque précédente m'amène à regretter que l'INSEE ne soit pas formellement partie prenante du dispositif BAN dans la mesure où le COG est la pierre angulaire du découpage communal et qu'il est sous leur responsabilité ...

**Comment by SnaLaposte15** [comment]
Il y a eu effectivement en peu de temps Fusion et Défusion et de notre côté nous avons pris du retard à "défusionner". C'est Ok désormais : 76420 BIHOREL et 76230 bois guillaume

**Comment by cquest** [comment]
Pas d'amélioration sur la livraison 20150705

```
 code_post |  libelle_acheminement  |  nb  
-----------+------------------------+------
 76230     | BOIS GUILLAUME BIHOREL | 4698
 76230     | QUINCAMPOIX            | 1314
 76230     | ISNEAUVILLE            | 1262
 76420     |                        | 2086
```

**Comment by SnaLaposte15** [comment]
Dans le SI Poste les données de juillet sont conformes à la réalité administrative à savoir :
76230 BOIS GUILLAUME
76420 BIHOREL.

A noter la mise en place de la loi "commune nouvelle" incite fortement au rapprochements de communes. Selon l'AMF près de 300 projets de regroupements sont prévus avant le 31 /12 date butoir des avantages financiers induits par cette opération. Le nombre de modifications (libellés de commuens...) va donc forrtement augmenter et il faudra être vigilant dans leur prise en compte
