### ISSUE TITLE
Pas de libellé d'acheminement sur la commune 76095 BIHOREL

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#21]
Les adresses de BIHOREL (76095) ont bien le code postal 76420 mais n'ont pas de libellé d'acheminement.

**Comment by ghost** [comment]
Soit on a un bug soit le fichier fourni en entrée par la poste ne comportait pas le couple 76095/76420

**Comment by parville** [comment]
Il  y a 2083 adresses ainsi orphelines.

**Comment by SnaLaposte15** [comment]
cf  #20 ; BOIS GUILLAUME et BIHOREL ayant défusionné, les 2 couples INSEE/CP ont été réinitialisés.
76108/76230 pour les adresses de BOIS GUILLAUME
76095/76420 pour les adresses de BIHOREL

**Comment by cquest** [comment]
Lié à https://github.com/etalab/ban-data/issues/20
