### ISSUE TITLE
BAN - 76 - 20150411 - Duplication d'adresses

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#28]
L'extraction BAN du 76 en date du 20150411 compte  490.289 adresses possédant chacune un identifiant unique (id).

Si on aggrège _code_post || '|' || nvl( numero || rep , '-') || '|' || nvl( nom_voie, nom_ld ) || '|' || nom_ld_ on trouve 14.153 valeurs distinctes présentes entre 2 et +40+ fois à l'identique.

Selon cet aggrégat, il y a 19.233 lignes en duplication, soit 3,9% des enregistrements.

**Comment by parville** [comment]
L'extraction BAN du 61 en date du 20150411 compte167.053 adresses possédant chacune un identifiant unique (id).

Si on aggrège code_post || '|' || nvl( numero || rep , '-') || '|' || nvl( nom_voie, nom_ld ) || '|' || nom_ld on trouve  4.448 valeurs distinctes présentes entre 2 et **36** fois à _l'identique_.

Selon cet aggrégat, il y a 6349 lignes en duplication, soit 3,8% des enregistrements.

**Comment by FrancoisVIGN** [comment]
Pourriez vous nous envoyer un lot d'exemple, une serie de Cle "ADRNIVX..." pour que nous regardions en détail les variations qui existent entre ces adresses.
bonne Journée

**Comment by cquest** [comment]
Même anomalie que sur https://github.com/etalab/ban-data/issues/4 et https://github.com/etalab/ban-data/issues/5
