### ISSUE TITLE
Les noms des fichiers sont trompeurs (osm/licence ouverte)

### ISSUE THREAD

**Issue by cquest** [etalab/ban-data#3]
Les noms utilisés pour les fichiers sont trompeurs:

adresses_licence_ouverte_2015-03-10_33.csv
et
adresses_osm_2015-03-10_33.csv

A remplacer par exemple par : 
adresses_licence_ban_2015-03-10_33.csv
et
adresses_odbl_2015-03-10_33.csv

**Comment by ghost** [comment]
on a modifié et je pense qu'on peut fermer cette issue

**Comment by cquest** [comment]
C'est ok pour la licence ODbL.

Par contre, le terme "licence ouverte" est toujours présent et porte à confusion avec la Licence Ouverte. C'est pour cette raison que j'avais proposé "licence BAN".

**Comment by ghost** [comment]
on a mis licence_ouverte-repartage, cela me semble plus clair, non?

**Comment by cquest** [comment]
J'ai renommé les fichiers en "BAN_licence_gratuite_repartage_NN.csv" pour être cohérent avec tout le reste du site ainsi que le texte de la licence lui même.
Le terme "Licence ouverte repartage" porterai trop à confusion avec la "Licence ouverte" d'Etalab.

Pour les fichiers ODbL, j'ai utilisé "BAN_odbl_NN.csv".

**Comment by ghost** [comment]
Ça me semble parfait Christian. Je reviens vers mon développeur pour lui demander de modifier ses programmes. Merci

**Comment by cquest** [comment]
Les noms des fichiers en licence gratuite de repartage sont toujours en "licence ouverte repartage"...

**Comment by rmpIGN** [comment]
Sur la livraison d'hier, les fichiers ont été renommés (dossier 20150524T215657 sur le sftp).

**Comment by cquest** [comment]
C'est désormais OK
