### ISSUE TITLE
BAN - 76 - 20150411 - Codes Postaux pour Dieppe 76217

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#30]
Historiquement Dieppe compte deux codes postaux suite à la fusion _ancienne_ avec Neuville-lès-Dieppe. 

La représentation des deux codes postaux laisse penser qu'il y a des erreurs.
_Par exemple, la zone en bleu contient une rue affectée à l'autre code postal_ ! 

![76-20150411-76217-zip](https://cloud.githubusercontent.com/assets/7741025/7252083/c4f706a6-e831-11e4-9216-862b0dd6d906.png)

**Comment by FrancoisVIGN** [comment]
Dans les données de La Poste intégrée à l'IGN, on observe bien deux codes postaux sur la communes 76217. (156 PA pour CP 76370 et 378 PA pour CP 76200)
Je vérifierai lors de la prochaine livraison des fichiers HEXA si une erreur est survenue lors de l'intégration de ces données dans les bases IGN.

**Comment by SnaLaposte15** [comment]
la RUE ALEXANDRE DUMAS est pour nous (POSTE) uniquement desservie par le CP 76200. Tout comme "une" des 2 avenue des canadiens (l'autre étant sur le code 76370) qui est proche de la zone "bleutée". 
Les 2 cp ont effectivement été conservés après la fusion des communes (de même que les problèmes liés à la conservation de libellés stricto sensu identiques.
