### ISSUE TITLE
BAN - 76 - 20150411 - Codes Postaux pour Le Havre 76351

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#31]
On repére visuellement des erreurs de Codes Postaux dans la BAN 20150411 pour Le Havre 76351

![76-20150411-76351-zip](https://cloud.githubusercontent.com/assets/7741025/7252605/eb284d8a-e836-11e4-80b9-2e2321099e6f.png)

**Comment by FrancoisVIGN** [comment]
Bonjour, Pourriez vous être plus explicite lorsque pensez détecter un problème ? Je crois qu'une simple carte avec des zones n'est pas suffisante pour pour permettre de comprendre le problème. 
La poste fait mention de 815 voie en 76600, 320 en 76610 et 661 en 76620.
Dans les communes pluri-distribuées, il est possible que l'information du CP ne soit pas fournie par La Poste. Dans ces cas la, nous plaçons par défaut un CP correspondant à la commune. Si vous disposez d'information complémentaire sur ces codes postaux, vous pouvez nous envoyer une table de correspondance qui nous aidera à fiabiliser la base. 
Attention cependant, ce problème de code postal sur les communes pluri-distribuées ne concerne que 4400 voies France Entière.

**Comment by parville** [comment]
Bonjour, je pense qu'il faudrait vous rapprocher de **La Poste** qui de mémoire participe activement à la #BAN ! ?

La carte montre de mon point de vue clairement qu'il y a non homogénéité spatiale dans les codes postaux affectés aux adresses puisque par exemple on a 48 codes verts au Nord-Ouest au mileu d'une zone de +1000 codes-rouges !

**Comment by SnaLaposte15** [comment]
Bonjour, pour les communes pluridistribuées et c'est le cas du Havre, toutes les voies que nous fournissons disposent d'un code postal. Parfois, une même voie peut être, pour une partie desservie par un CP et pour partie par une autre. C'est ainsi le cas de la Rue commandant Cousteau.
Par ailleurs, sans entrer dans le détail de nos organisations, il n'y a pas toujours de cohérence entre un CP et une zone géographique et cartographique. L'affectation des CP et les conditions de distribution dépendent de plus de critères que le seul aspect cartographique.
