### ISSUE TITLE
BAN - 61 - 20150411 - Enregistrements sans Codes Postaux

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#33]
Il y a 4 enregistrements dans 2 communes distinctes qui n'ont pas de Code Postal

![61-2015-04-27_11h20_05](https://cloud.githubusercontent.com/assets/7741025/7346002/7bdc62f6-ecda-11e4-82a7-68c660448e4e.png)

**Comment by cquest** [comment]
Même problème sur Toulouse, par exemple "Rue des 36 Ponts", qui a 116 adresses avec code postal 31400 et 2 adresses sans code postal (90B et 98)

voir https://github.com/etalab/addok/issues/59

**Comment by FrancoisVIGN** [comment]
Ceci est effectivement un problème sur les données. je continu mon investigation.

**Comment by cquest** [comment]
J'en dénombre 10888 sur la livraison d'avril.

**Comment by FrancoisVIGN** [comment]
Peut on nous fournir une liste de Cleabs "ADRNIVX" ?

**Comment by SnaLaposte15** [comment]
Sur le cas de Toulouse "Rue des 36 ponts", le n° 98 est bien distribué par le CP 31400. En revanche, le 98B n'est à ce jour pas affecté à une "tournée de dsitribution" et ne dispose pas encore de CP affecté (même si celui ci sera le 31400). Une action est en cours

**Comment by SnaLaposte15** [comment]
Juste pour completer et pour les exemples de la première demande, toutes ces adresses sont bien sur le CP 61290

**Comment by cquest** [comment]
Il n'y a plus aucune adresse sans CP (livraison du 22/1/2017), je ferme...
