### ISSUE TITLE
Absence d'accès à la version FANTOIR utilisée par la BAN

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#37]
Bonjour, le fait que le FANTOIR reste bloqué sur data.gouv.fr à Juin 2014 pose des soucis de croisement avec les données de la BAN.

Comment se fait-il que cette pièce maitresse n'est pas republiée depuis lors ? 

Merci

**Comment by parville** [comment]
Mise à jour Avril 2015 publiée ce jour !

**Comment by cquest** [comment]
Je vais la remettre à jour pour mes traitements...

**Comment by cquest** [comment]
voir https://github.com/etalab/ban-data/commit/fb375be342fbd33dbc1afbcf89e7de647c0c1fbc
