### ISSUE TITLE
BAN 61 - 20150411- Présence de NOM_LD commençant par MLN

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#38]
Dans le fichier BAN du 61 en date du 11/04/2015 on trouve 217 NOM_LD qui commencent par 'MLN(espace)' où 'MLN' est l'abréviation de 'MOULIN'.

**Comment by parville** [comment]
En fait on trouve aussi 'FRM', 'CHT','HAM', 'LOT','PLA', 'CTR' etc ....

PS : CTR = Contour et non pas CenTRe !
PPS : VAU = Veau ? (dans VAU SOURI)

**Comment by parville** [comment]
Attention AVE désigne bien semble-t-il un nom de lieu-dit !

**Comment by cquest** [comment]
NOM_LD n'est pas actuellement désabrégé, seul nom_voie l'est en principe.

**Comment by FrancoisVIGN** [comment]
je confirme ce que dit Christian

**Comment by parville** [comment]
Bonjour, on en est où 18 mois après ?  Situation inchangée ? Pourquoi !!!
