### ISSUE TITLE
BAN 61 - 20150411- NOM_LD débutant par L'(espace)

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#40]
Dans le fichier BAN 61 du 11 Avril 2015, on trouve des adresses avec un NOM_LD mal structuré car comportant un espace après un ' : "L' ENTRERUE" commune de RAI (61342)

**Comment by FrancoisVIGN** [comment]
Bonjour, ce genre de cas ne devrait il pas faire l'objet d'une correction collaborative plutôt qu'être remonté sur le github, espace normalement réservé aux alertes et aux bugs ?

**Comment by cquest** [comment]
C'est typiquement une correction à appliquer de façon automatique. Quels sont les cas où un "L'" ou"D'" doivent être suivis d'un espace ?

**Comment by parville** [comment]
@cquest , je suis d'accord à 200%

**Comment by FrancoisVIGN** [comment]
Je ne comprends pas ta question @cquest, 
Pour le nom de LD, je vais corriger ca moi même dans la base.

**Comment by cquest** [comment]
Je voulais savoir si vous aviez connaissance de cas particuliers avec des apostrophes suivis d'espace qu'il faudrait conserver dans un traitement automatique.

**Comment by FrancoisVIGN** [comment]
Je n'en ai pas connaissance. Je suis déjà surpris par cet espace.

**Comment by FrancoisVIGN** [comment]
La correction a été apportée sur la base. plusieurs cas semblables ont été détectés. 
Leurs modifications seront faites par les collecteurs au fur et a mesure de leurs avancées.

**Comment by FrancoisVIGN** [comment]
Ce problème est il toujours d'actualité ?

**Comment by cquest** [comment]
Je ne trouve plus de cas de ce type sur les dernières livraisons.
