### ISSUE TITLE
BAN 61 - 20150411- Noms de voies commençant par 'pla(espace)'

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#42]
Dans la BAN 61 on trouve par exemple NOM_VOIE = 'pla de salzdahlum'.
Il est étonnant qu'un tel nom de voie se retrouve aussi qualifié de lieu-dit.

**Comment by FrancoisVIGN** [comment]
Bonjour ceci entre dans les corrections en cours dans la base adresse et dont il a été fait mention dans #35

**Comment by cquest** [comment]
Voir https://github.com/etalab/ban-data/issues/35
