### ISSUE TITLE
BAN 61 - 20150411- NOM_LD commençant par 'PTE(espace)'

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#43]
Dans la BAN 61 on trouve par exemple NOM_LD = 'PTE D'AUBE' pour un NOM_VOIE = "Porte d'aube".

**Comment by FrancoisVIGN** [comment]
Bonjour ceci entre dans les corrections en cours dans la base adresse et dont il a été fait mention dans #35

**Comment by FrancoisVIGN** [comment]
Afin d'éviter la duplicité des tickets, pourrait on concentrer ces tickets sur de mauvaises abréviations en un seul, avec la liste de toutes les mauvaises abréviations détectées ?

**Comment by cquest** [comment]
voir https://github.com/etalab/ban-data/issues/35
