### ISSUE TITLE
BAN - 61 - 20150411 - 5 adresses très incohérentes Commune <> X,Y

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#46]
Sur le code INSEE 61443 on trouve 5 adresses au demeurant peu convaincantes dont les coordonnées pointent à X+90 Km de là 

![61-hors-commune](https://cloud.githubusercontent.com/assets/7741025/7704650/0089fca4-fe40-11e4-9a70-ccbe2dacff31.png)

REF =  ADRNIVX_0000000340372685 à ADRNIVX_0000000340372689

Prévoir un contrôle qualité de cohérence ?

**Comment by FrancoisVIGN** [comment]
Ceci a été corrigé.
