### ISSUE TITLE
Données BAN repartage - Version disponible,  nom des fichiers et sélection 

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#49]
Bonjour, il est dommage:
- de ne pas savoir de quand datent les données disponibles sur le site
- que les fichiers ne portent pas cette date de génération dans leur nom 
- que l'on soit obligé de télécharger les 900 Mo pour n'en utiliser qu'une sous-partie

**Comment by cquest** [comment]
Je vais ajouter un fichier supplémentaire dans l'archive téléchargeable pour avoir:
- un hash de chaque fichier pour vérifier son intégrité
- la date de génération de l'archive

**Comment by cquest** [comment]
Un fichier "contenu.txt" est désormais ajouté à l'archive ZIP téléchargeable.
Il contient en première ligne la date/heure de la livraison, puis un hash SHA1 pour chaque fichier CSV.
La date de livraison va être ajoutée sur le site ainsi qu'un téléchargement par département.
