### ISSUE TITLE
Données en ligne au 20150610 - doublons

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#50]
Bonjour, je ne comprends pas pourquoi on peut avoir des triplons d'adresse identiques en tout point sauf l'id ! Pouvez-vous convenir que le plus petit des id doit seul perdurer.

Exemple (ça ne manque pas)
- ADRNIVX_0000000312893409
- ADRNIVX_0000000312893408
- ADRNIVX_0000000312893407

**Comment by FrancoisVIGN** [comment]
N'est ce pas le même sujet que issues #4 ou #5  ?

**Comment by parville** [comment]
Bonjour, s'agissant d'une nouvelle livraison j'aurai dit à moitié !

**Comment by cquest** [comment]
Anomalie identique, je ferme ici.
