### ISSUE TITLE
Données 974 et 976

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#51]
Les données téléchargées  ce 30 Juin pour 974 et 976 me plongent dans un abime de perplexité. 

La BAN confirme la validité des fichiers produits ?

**Comment by cquest** [comment]
Il y a effectivement un problème... 
id;nom_voie;id_fantoir;numero;rep;code_insee;code_post;alias;nom_ld;nom_afnor;libelle_acheminement;x;y;lon;lat;nom_commune
ADRNIVX_0000000000208866;;;14;B;97611;"";"";"";;;523920;8586463;45.220392683176;-12.7865096240558;Mamoudzou
ADRNIVX_0000000000208863;;;10;"";97611;"";"";"";;;523835;8586593;45.2196085032245;-12.7853347135588;Mamoudzou
ADRNIVX_0000000000208855;;;0;"";97611;"";"";"";;;523919;8586530;45.2203829439809;-12.7859037643561;Mamoudzou
ADRNIVX_0000000000208854;;;0;"";97611;"";"";"";;;523930;8586543;45.220484192355;-12.7857861232991;Mamoudzou
ADRNIVX_0000000000208853;;;0;"";97611;"";"";"";;;523917;8586507;45.220364697017;-12.7861117640848;Mamoudzou
ADRNIVX_0000000000208852;;;0;"";97611;"";"";"";;;523875;8586494;45.2199778242865;-12.7862296434453;Mamoudzou
ADRNIVX_0000000000208847;;;0;"";97611;"";"";"";;;523849;8586522;45.2197380495558;-12.7859766447841;Mamoudzou

**Comment by cquest** [comment]
Corrigé dans la livraison du 5 juillet.
