### ISSUE TITLE
Arrondissements en double

### ISSUE THREAD

**Issue by baloran** [etalab/ban-data#53]
Hello, lorsque l'on recherche Marseille, Paris ou Lyon avec l'API, nous tombons sur des adresses avec des `id : "75117_XXXX_13e667"` et du `type: "street"` ce qui fais que les arrondissements sont en double du fait que d'autres sont du `type: "city"`. 

http://api-adresse.data.gouv.fr/search?q=paris par exemple.

**Comment by FrancoisVIGN** [comment]
je pense que l'erreur vient de la structure des données en sortie du géocodeur.

**Comment by yohanboniface** [comment]
Ce sont je crois les adresses "empilées", i.e. sans coordonnées précises et donc mise au centre de la commune. Il faudrait je pense les supprimer de notre côté pour l'instant. Et leur donner des vraies coordonnées côté IGN ;)

cc @cquest

**Comment by cquest** [comment]
L'autocompletion avec "Paris" retourne effectivement:
- la commune en premier (75056),
- puis 2 arrondissements mais nommés simplement "Paris" qui est à mon avis une erreur dans la préparation des données json pour addok
- puis ensuite des lieux-dits "Paris" dans d'autres communes.

La première réponse est donc bonne (ouf), mais pas les 2 et 3ème... je regarde pourquoi ces pseudo rues sont générées dans le json.

**Comment by cquest** [comment]
Dans les données livrées par l'IGN, il y a 15 adresses avec numéro dans le 17ème arrondissement qui ne comportent pas de nom_voie ni nom_ld et 3 dans le 18ème arrondissement.
L'export json génère donc une rue sans nom avec ces numéros et c'est elle qui sort en 2ème et 3ème position.

Voici la liste pour Paris:
ADRNIVX_0000000340141360
ADRNIVX_0000000328412434
ADRNIVX_0000000340145583
ADRNIVX_0000000340141359
ADRNIVX_0000000340141361
ADRNIVX_0000000340141362
ADRNIVX_0000000340141363
ADRNIVX_0000000340141364
ADRNIVX_0000000340141365
ADRNIVX_0000000340141366
ADRNIVX_0000000340141367
ADRNIVX_0000000340141368
ADRNIVX_0000000340141369
ADRNIVX_0000000340141370
ADRNIVX_0000000340141371
ADRNIVX_0000000340141372
ADRNIVX_0000000340145584
ADRNIVX_0000000340145585
ADRNIVX_0000000340145586

Il y en a 59734 sur la livraison d'hier.

Je suggère de filtrer ces adresses numérotées, mais sans noms de voie ou de lieu dit.

**Comment by cquest** [comment]
Cause liée à https://github.com/etalab/ban-data/issues/36

**Comment by FrancoisVIGN** [comment]
la liste de cleabs comporte bien des noms de rues (Rue Mere Teresa, Rue Severiano de herdia, Rue Madeleine Reberioux, place blanche lefebvre). 
Le problème sur cette liste de clé est voie en découlant. Un traitement IGN est en cours de préparation pour rapatrier l'ensemble de ces voies manquantes
