### ISSUE TITLE
Des rues qui doublonnent les grosses villes

### ISSUE THREAD

**Issue by Ismael-Hery** [etalab/ban-data#55]
Hello,

Contexte:
- On utilise la BAN pour de la suggestion sur de la saisie d'adresse d'habitation pour trouver des entreprises qui recrutent autour
- L'utilisateur peut saisir son adresse précise ou une rue ou une ville etc.

Mon problème:
Pour les grandes villes (mettons Lyon), quand je cherche Lyon ça me remonte bien la "city" Lyon mais aussi plusieurs objets de type "street" qui ont le label Lyon et qui ajoute du bruit dans ma liste de suggestion.

```
{
        "properties": {
            "context": "69, Rh\u00f4ne, Rh\u00f4ne-Alpes",
            "city": "Lyon",
            "type": "city",
            "adm_weight": "5",
            "id": "69123",
            "population": "484",
            "postcode": "69000",
            "score": 0.9909090909090909,
            "label": "Lyon",
            "name": "Lyon"
        },
        "type": "Feature",
        "geometry": {
            "coordinates": [4.8353, 45.7579],
            "type": "Point"
        }
    }, {
        "properties": {
            "context": "69, Rh\u00f4ne, Rh\u00f4ne-Alpes",
            "city": "Lyon",
            "type": "street",
            "id": "69382_XXXX_484b68",
            "citycode": "69382",
            "postcode": "69002",
            "score": 0.9278909090909091,
            "label": "Lyon",
            "name": "Lyon"
        },
        "type": "Feature",
        "geometry": {
            "coordinates": [4.820993, 45.745509],
            "type": "Point"
        }
    }
```

J'ai trouvé un contournement mais je suis pas sûr que ces "streets" soit pertinentes, dites moi.

Merci pour votre aide !

**Comment by FrancoisVIGN** [comment]
Est ce le même problème que le #53 puisqu'il parle aussi de Street et City. 
D'où viennent ces données ? du résultat du geocodeur ?

**Comment by Ismael-Hery** [comment]
Oui ça doit être la même chose que #53.

Ces données viennent d'appel au WS du géocodeur de la BAN.

**Comment by FrancoisVIGN** [comment]
Cela est donc lié au processus de travail du géocodeur.

**Comment by cquest** [comment]
Cela vient des données livrées par l'IGN, je vais ajouter un filtre pour ne pas perturber le géocodeur et éliminer les adresses numérotées sans nom de voie ni de lieu dit.
Identique à https://github.com/etalab/ban-data/issues/53 et la cause est identifiée sur https://github.com/etalab/ban-data/issues/36

**Comment by FrancoisVIGN** [comment]
Un traitement IGN est en cours de préparation pour rapatrier l'ensemble de ces voies manquantes
