### ISSUE TITLE
*NOBDUNI* dans nom_ld

### ISSUE THREAD

**Issue by cquest** [etalab/ban-data#6]
A quoi correspond ceci ?

**Comment by ghost** [comment]
on n'a pas filtré ça, il faut qu'on l'ajoute. ces adresses ont été vérifiées sur le terrain et ne correspondent à rien

**Comment by cquest** [comment]
```
ADRNIVX_0000000270772682: *NOBDUNI*TOUR EIFFEL
```

C'est peut être absent de la BD Uni mais bien présent sur le terrain comme lieu dit.
Il faudrait donc filtrer le "_NOBDUNI_" mais pas le reste du champ ou alors laisser en l'état mais le documenter.

**Comment by ghost** [comment]
la tour eiffel n'est pas un lieu dit. C'est un point d'intérêt touristique. on l'a comme tel dans une autre classe de la BDUni.

**Comment by cquest** [comment]
Corrigé dans la livraison du 11-04-2015
