### ISSUE TITLE
Les villes des DOM ont des coordonnées fausses

### ISSUE THREAD

**Issue by frodrigo** [etalab/ban-data#60]
Saint-Denis (de la Réunion) en Angleterre
Cayenne dans le Golf de Guinée
...

**Comment by frodrigo** [comment]
Une correction possible des données en vue ?

**Comment by cquest** [comment]
Corrigé par https://github.com/etalab/ban-data/commit/f601a0c761e2829ea495291b11023992a033c57e

**Comment by cquest** [comment]
Les lat/lon étaient inversées dans le fichier source, maintenant elles sont recalculées pour éviter ce genre de problème.
https://github.com/etalab/ban-data/commit/70367691f5067822866c6536e3db19284a6a0338
