### ISSUE TITLE
Disparité des valeurs du champ type pour les communes

### ISSUE THREAD

**Issue by frodrigo** [etalab/ban-data#64]
Le champ type prend plusieurs valeurs dans les données pour les communes. Je suppose qu'il est déduit de l'importance de la commune. Mais il n'y a déjà un champ pour ça. Le fait d'avoir plumiers valeurs complique le processus de filtrage.

Ce problème est en particulier vrais pour addok qui ne peut filtrer que sur un seul type.

Je propose d'utiliser une seule valeur de type pour toutes les communes et laisser l'utilisateur libre de faire la déduction qu'il souhaite depuis le champ importance et de ce qu'il veut d'autres.

(idem BANO)

**Comment by frodrigo** [comment]
https://github.com/etalab/ban-data/blob/9cd39d465b92b2edda0f944ab26b431765641f99/scripts/out_pg2json.sh#L49
Il faut mettre ici la même valeur pour tout le monde

**Comment by cquest** [comment]
Toutes les communes sont désormais en type=municipality

**Comment by parville** [comment]
:worried: Désolé mais il y a une régression dans la livraison de la semaine 2017S5 (30 Janvier)  :worried:

Il faut donc réouvrir l'issue.

Exemple sur **BAN_obdl_76** 👍 

{"id": "76001","type": "**town**","name": "Allouville-Bellefosse","postcode": "76190","citycode": "76001","lat": 49.595470,"lon": 0.677070,"city": "Allouville-Bellefosse","context": "76, Seine-Maritime, Normandie (Haute-Normandie)", "population": 1.2, "adm_weight": 1, "importance": 0.075}
{"id": "76002","type": "**village**","name": "Alvimare","postcode": "76640","citycode": "76002","lat": 49.605368,"lon": 0.630971,"city": "Alvimare","context": "76, Seine-Maritime, Normandie (Haute-Normandie)", "population": 0.5, "adm_weight": 1, "importance": 0.075}

**Comment by cquest** [comment]
Je vais regénérer les fichiers avec ce nouveau code.

**Comment by cquest** [comment]
Ils sont disponibles sur https://bano.openstreetmap.fr/BAN_odbl/

**Comment by frodrigo** [comment]
L'issue peut-être fermé.
