### ISSUE TITLE
76451 Mt-St-Aignan - deux voies ... pour une seule

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#65]
Sur 76451, Mont-Saint-Aignan, on trouve des points BAN sur 
- rue jacques boutrolle
- rue jacques boutrolle d'estaimbuc

La voie s'appelle formellement **rue jacques boutrolle d'estaimbuc** 
Et le libellé AFNOR proposé est à pleurer   _RUE ASP J BOUTROLLE D ESTAIMBUC_

Merci d'unifier les deux noms et d'oublier ce libellé AFNOR  abscon  !

**Comment by SnaLaposte15** [comment]
De notre côté, la notion "rue jacques boutrolles" est identifiée comme une appellation" locale" (cad usité largement localement). Le seul libellé officiel comporte RUE JACQUES BOUTROLLE D ESTAIMBUC. Nous vérifions auprès de la mairie s'il s'agit là du libellé officiel où si la notion d'ASPIRANT (ASP dans le libellé standardisé) a une réelle existence.

**Comment by cquest** [comment]
Le nom a été mis à jour dans les données livrées, par contre, pour certaines adresses on a un alias: "R JACQUES BOUTROLLE" et un id_fantoir, et pas pour d'autres.
Ceci génère du coup de 2 lignes dans les json.
