### ISSUE TITLE
Détecter en amont les doublons de dénominations 

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#71]
Par exemple la BAN propose à Bois-Guillaume (INSEE 76108à deux entrées qui devraient n'en faire qu'une, si la tolérance aux accents étaient appliquées 

```
        "name": "Chemin de la Breteque", 
        "id": "76108_0080_a4f6f3", 

        "name": "Chemin de la Bretèque",
        "id": "76108_0080_d9e3bf",
```

Merci

**Comment by cquest** [comment]
Je vais privilégier le libellé avec accent et regrouper.
