### ISSUE TITLE
ID en doublon...

### ISSUE THREAD

**Issue by cquest** [etalab/ban-data#75]
Sur la livraison du 10-01-2016, l'ID ADRNIVX_0000000287161829 figure en 2 exemplaires dans 2 départements différents 78 et 92).

ADRNIVX_0000000287161829;avenue des puits;0870;31;"";78126;78170;"";"";LA CELLE ST CLOUD;637306.7;6860498.3;2.1457933767659;48.8414814464155;La Celle-Saint-Cloud

ADRNIVX_0000000287161829;;0570;31;"";92076;92420;"";"";VAUCRESSON;637306.7;6860498.3;2.1457933767659;48.8414814464155;Vaucresson

**Comment by FrancoisVIGN** [comment]
Ce point est il toujours d'actualité?? je croyais que les scripts avait été modifié depuis à cela

**Comment by cquest** [comment]
Ce défaut semble réglé sur les livraison actuelles. Je ferme.
