### ISSUE TITLE
Rue Nationale (Chemille-Melay) (Chemillé-Melay) à Chemillé-en-Anjou

### ISSUE THREAD

**Issue by cquest** [etalab/ban-data#80]
Doublon dans le nom de l'ancienne commune (nom_voie + ancienne_commune) après post-traitement nom anciennes communes fusionnées à cause de l'accentuation.

ADRNIVX_0000000263685256

**Comment by FrancoisVIGN** [comment]
Pour confirmation : 
Sur les données le nom n'est pas "Route Nationale (Chemille-Melay)".
Peut-être que nos processus internes de production ont corrigé le tir depuis la publication de l'Issue. 
Peut on confirmer ?
