### ISSUE TITLE
Version du COG de l'INSEE

### ISSUE THREAD

**Issue by cquest** [etalab/ban-data#9]
Quelle est la version du COG de l'INSEE utilisé ?

**Comment by ghost** [comment]
je suppose celle qu'ils nous ont livrée dernièrement. je peux me renseigner

**Comment by FrancoisVIGN** [comment]
S'il s'agit de loisey-culey, la dé-fusion/scission a été prise en compte suite à la décision du tribunal administratif de Nancy le 7 février 2014.
Sinon, les mises à jour du COG 2015 viennent d'être intégrées dans les dernières semaines.

**Comment by cquest** [comment]
Je pensais plus aux fusions du 1/1/2015 qu'à cette scission (qui sera en vigueur le 1/1/2016).
Je vais donc utiliser mon COG2015 non officiel pour les contrôles.

J'ai un doute sur l'utilisation du COG2015...

select count(*) from ban_all where code_insee~'14474|25035|28185|38152|60570|60570|73263|72137|69255|61486|61375|61292|77316|14178|25034|28069|38024|60417|61031|61109|61177|61223|61249|61377|61410|61417|61511|61513|69221|71578|71138|72069|72162|72207|72258|72318|73264|77166';

## count 

 14768
(1 row)

Il semblerait qu'on soit plutôt sur la version 2014 du COG.

**Comment by FrancoisVIGN** [comment]
je ne comprend pas le problème... Où sont réellement les erreurs ? parce que compter les adresses correspondantes aux INSEE n'a aucune signification pour moi.

**Comment by parville** [comment]
Personnellement il me semble que la requête a du sens. 
Il est anormal de trouver des adresses sur des codes INSEE qui ne correspondent plus à des communes légalement existantes ! 
L'autre sens est valable si on considére le délai de réintroduction dans les données IGN du Code Insee de Bihorel (76) dans le RGE après la défusion d'avec Bois-Guillaume.

**Comment by FrancoisVIGN** [comment]
Je ne critiquais pas la requête en elle même, mais plutôt le fait que ne connaissant pas le nombre attendu par cette requête, je ne sais pas comment l'interpréter. Dans les données IGN, le compte sera nécessairement différent du fait des nettoyages opérés. 
Sur les 37 INSEE de la liste fournie par Christian, il y a 24 INSEE qui ont disparu suite à leurs fusions avec les 13 INSEE qui sont conservés.
INSEE conservés : 14474|25035|28185|38152|60570|60570|73263|72137|69255|61486|61375|61292|77316
INSEE disparus : 14178|25034|28069|38024|60417|61031|61109|61177|61223|61249|61377|61410|61417|61511|61513|69221|71578|71138|72069|72162|72207|72258|72318|73264|77166

D'où les 14767 adresses conservée ;-)

**Comment by parville** [comment]
Bonjour, ce détail m'avait échappé. 
D'accord ! 

Disons donc qu'il faudrait vérifier sur le périmétre des INSEE disparus que le résultat total est à 0 !
Et à l'inverse, commune conservée par commune conservée, que le résultat pour chacune n'est pas 0 !
Utilisateur en aval, j'insiste sur l'enjeu du délai de mise à jour des évolutions administratives dans un sens (fusion) comme dans l'autre (défusion). Après ca pose le cas des créations de doublons de voies en cas de fusion que les autorités devraient avoir l'obligation d'anticiper ?

**Comment by cquest** [comment]
Oups... désolé pour la requête qui mélangeait les codes restants et ceux disparus depuis le 1/1/2015.

select code_insee, nom_commune, count(*) from ban_all where code_insee~'14178|25034|28069|38024|60417|61031|61109|61177|61223|61249|61377|61410|61417|61511|61513|69221|71138|72069|72162|72207|72258|72318|73264|77166' group by 1,2;

retourne 1 seule adresse (ADRNIVX_0000000273006377) sur l'ancienne commune de Roullée (72258), on y est presque !

Attention, 71578 (Clux-Villeneuve) est une nouvelle commune, je l'ai donc retirée de la requête.

**Comment by parville** [comment]
:+1:
