### ISSUE TITLE
Format du JSON pour "population", "adm_weight", "importance"

### ISSUE THREAD

**Issue by parville** [etalab/ban-data#94]
Bonjour, 

le fichier JSON contient plusieurs valeurs de type numérique. Cependant certaines sont entre "" (lon, lat )  et d'autres non ("population", "adm_weight", "importance"). 

Est-il envisageable d'homogénéiser le format de présentation des données numériques ?

Merci

**Comment by cquest** [comment]
Les lat/lon des communes comportaient des "
